### ISSUE TITLE
[Feat] 가상 서비스 삭제

### ISSUE THREAD

**Issue by yjeongc** [AegisLenz/AegisLenz-BE#105]
## 🔥 Issue
사용자가 실제 이용할 수 있는 서비스만 로그에서 남김

## ✅ TODO
- [ ]  로그를 eventSource로 클러스터링
- [ ] 실제 서비스가 기록되어 있는 DB와 로그를 비교
- [ ] DB에 존재하지 않는 event는 삭제
- [ ] Record 필드가 존재하는 로그 형식으로 변경
