### ISSUE TITLE
[Feat] 최소권한정책 템플릿 MongoDB에 저장하기

### ISSUE THREAD

**Issue by jyjyjy25** [AegisLenz/AegisLenz-BE#34]
## 🔥 Issue
최소권한정책 템플릿 MongoDB에 저장하기

## ✅ TODO
- [x] 정책 Model 스키마 설계
- [x] iam-policy 레포의 AWS 최소권한정책 DB를 submodule로 설정
- [x] iam-policy 레포의 AWS 최소권한정책 DB 데이터 MongoDB에 저장
