### ISSUE TITLE
[Feat] IAMBERT 모델 배포

### ISSUE THREAD

**Issue by jyjyjy25** [AegisLenz/AegisLenz-BE#6]
## 🔥 Issue
학습된 IAMBERT 모델을 FastAPI와 함께 배포한다.

## ✅ TODO
- [x] IAMBERT 모델 로드
- [x] 실시간 로그 수집 API 구현
- [x] 공격 탐지 API 구현
- [x] SSE 방식으로 공격 alert 구현
