### ISSUE TITLE
[Feat] 최소권한 생성 로그 ES에서 가져오기

### ISSUE THREAD

**Issue by yjeongc** [AegisLenz/AegisLenz-BE#79]
## 🔥 Issue
최소권한 생성 로그 ES에서 가져오기

## ✅ TODO
- [x]  최소권한 생성 로그 ES에서 필요한 필드만 추출하여 가져옴
- [x] username이 없는 경우엔 root로 대체
- [ ] ec2 필드 로그 경로에 맞게 수정
