### ISSUE TITLE
[Feat] 프론트엔드 대시보드 SSE 구현 가속화 및 구체화 작업

### ISSUE THREAD

**Issue by chae1xxlos** [AegisLenz/AegisLenz-BE#89]
## 🔥 Issue
 프론트엔드 대시보드 SSE 구현 가속화 및 구체화 작업

## ✅ TODO
- [ ]  프리로딩 캐시 로직 구현
- [ ] 데이터 처리 지연 문제 해결
- [ ] 프론트엔드 실시간 반응성 향상
- [ ] 로드 밸런싱
